import React from "react";
import Link from "next/link";
import Head from "next/head";
import { useRouter } from "next/router";
import { useWindowWidth } from "@react-hook/window-size";
import DashboardMain from "./components/DashboardMain";
import Customers from "./components/Customers";
import Products from "./components/Products";
import Account from "./components/Account";
import Settings from "./components/Settings";
import Elevators from "./components/Elevators";
import item from "./item.json";
import { MdSpaceDashboard, MdSettings, MdNotifications } from "react-icons/md";
import { GiElevator } from "react-icons/gi";
import { FaQuestionCircle, FaUserAlt, FaUserFriends } from "react-icons/fa";
import {
  RiShoppingBagFill,
  RiExternalLinkLine,
  RiMessage2Fill,
} from "react-icons/ri";
import {
  AiOutlineMenuFold,
  AiOutlineMenuUnfold,
  AiOutlineMenu,
  AiOutlineSearch,
} from "react-icons/ai";
function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

export default function Dashboard() {
  const router = useRouter();
  const [active, setActive] = React.useState("customers");
  const [show, setShow] = React.useState(false);
  const onlyWidth = useWindowWidth();
  const [showMessage, setShowMessage] = React.useState(false);
  const [showUserMenu, setShowUserMenu] = React.useState(false);
  const [messages] = React.useState(item.messages);

  return (
    <div className="relative mx-auto flex flex-col items-center justify-between bg-[#061325] h-[100vh] overflow-y-scroll ">
      <Head>
        <title>AKE Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://ake.com.tr/uploads/images/logo.png" />
      </Head>

      <div className="fixed top-0 flex flex-row max-w-screen-xl justify-between items-center w-full h-[70px] bg-[#071326] p-2 z-10">
        <div className="flex flex-row items-center text-white gap-x-4 md:gap-x-8 w-full ">
          <AiOutlineMenuUnfold
            className={
              show
                ? "bg-gray-600 text-gray-300  w-10 h-10 rounded-full cursor-pointer p-2 md:ml-2 hover:bg-gray-500 hidden md:block"
                : "hidden"
            }
            onClick={() => setShow(!show)}
          />
          <AiOutlineMenu
            className="md:hidden bg-gray-600 text-gray-300  w-10 h-10 rounded-full cursor-pointer p-2"
            onClick={() => setShow(!show)}
          />
          <AiOutlineMenuFold
            className={
              show
                ? "hidden"
                : "bg-gray-600 text-gray-300  w-10 h-10 rounded-full cursor-pointer p-2 md:ml-2 hover:bg-gray-500 hidden md:block"
            }
            onClick={() => setShow(!show)}
          />
          <Link href="/dashboard" className="w-[140px] h-auto object-cover">
            <img src="https://ake.com.tr/uploads/images/logo.png" alt="logo" />
          </Link>
          <AiOutlineSearch
            size={25}
            className="hidden md:block absolute left-[21%] text-[#344050]"
          />
          <input
            type="text"
            placeholder="Search..."
            className="w-[250px] h-10 hidden md:block border-[1px] font-bold text-[#344050] rounded-full px-10 border-[#344050] bg-[#061325] "
          />
        </div>
        <div className="flex flex-row items-center justify-end gap-x-2 w-1/2 relative">
          <MdSettings
            size={25}
            className="text-blue-500 cursor-pointer animate-spin"
          />
          <div className="absolute top-[9px] right-[81px] animate-ping w-6 h-6 border-blue-500 border-2 rounded-full" />

          <MdNotifications
            onClick={() => setShowMessage(!showMessage)}
            size={25}
            className={
              showMessage
                ? "text-white cursor-pointer hover:text-red-500"
                : "text-red-500 cursor-pointer hover:text-white"
            }
          />
          {showMessage && (
            <div className="absolute top-12 right-8 z-10 shadow-xl  w-[275px] h-[414px] rounded-lg flex flex-col border-[1px] border-[#132238]">
              <div className="flex flex-row justify-between items-center bg-[#0e1c2f] h-[35px] px-4 ">
                <p className="text-[#d7e1ee] ">Notifications</p>
                <p className="text-[#2c7be5] text-[14px] hover:underline cursor-pointer ">
                  Marked all as read
                </p>
              </div>
              <p className="px-4 text-[#6c798c] bg-[#132238] h-6 font-bold text-sm">
                NEW
              </p>
              {messages.map((message, i) => (
                <div
                  key={i}
                  className={
                    i === messages.length - 1
                      ? "h-[80px] hover:bg-black hover:cursor-pointer flex flex-row items-center bg-[#061325] px-4 gap-x-4 "
                      : "h-[80px] flex flex-row items-center bg-[#061325] hover:bg-black hover:cursor-pointer px-4 gap-x-4 border-b-[1px] border-gray-500"
                  }
                >
                  <img
                    src="https://falconreactbs4.prium.me/static/media/1.38f0341f.jpg"
                    alt="logo"
                    className="w-10 h-10 object-cover rounded-full "
                  />
                  <div className="text-[#edf2f9] text-[12px] ">
                    <p>
                      <strong>{message.author}</strong> : {message.content}
                    </p>
                    <p className="flex flex-row items-center gap-x-2 ">
                      <RiMessage2Fill size={20} />
                      <span className="text-gray-500">just now</span>
                    </p>
                  </div>
                </div>
              ))}
              <p className="px-4 text-[#6c798c] bg-[#132238] h-6 font-bold text-sm">
                EARLIER
              </p>
              <div className="h-[80px] flex flex-row items-center bg-[#0e1c2f] px-4 gap-x-4 py-4 hover:bg-black hover:cursor-pointer">
                <img
                  src="https://falconreactbs4.prium.me/static/media/1.38f0341f.jpg"
                  alt="logo"
                  className="w-10 h-10 object-cover rounded-full "
                />
                <div className="text-[#edf2f9] text-[12px] ">
                  <p>
                    The forecast today shows a low of 20℃ in California. See
                    today's weather. 🌤️
                  </p>
                  <p className="flex flex-row items-center gap-x-2 ">
                    <RiMessage2Fill size={20} />{" "}
                    <span className="text-gray-500">9 hours ago</span>
                  </p>
                </div>
              </div>
              <p className="text-[#2c7be5] text-[14px] hover:underline cursor-pointer bg-[#0e1c2f] text-center border-t-[1px] border-gray-500 ">
                View all
              </p>
            </div>
          )}
          <img
            className="w-10 h-auto rounded-full cursor-pointer"
            onClick={() => setShowUserMenu(!showUserMenu)}
            src="https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png"
            alt="user"
          />
          {showUserMenu && (
            <div className="absolute top-12 text-[#8894a6] font-bold right-0 z-50 bg-[#0e1c2f] py-2 w-[160px] h-[100px] flex flex-col items-center rounded-lg shadow-xl justify-between border-[1px] border-[#132238]">
              <p className="text-[#f5803e]">Serif Colakel</p>
              <p className="hover:text-white cursor-pointer">
                Profile & Account
              </p>
              <p
                className="hover:text-white cursor-pointer"
                onClick={() => {
                  sleep(500).then(() => {
                    router.push("/login");
                  });
                }}
              >
                Logout
              </p>
            </div>
          )}
        </div>
      </div>
      <div className="flex flex-row w-full max-w-screen-xl h-full">
        <div
          className={
            onlyWidth > 768
              ? "w-[8%] h-full text-white"
              : !show
              ? "w-[8%] h-full text-white"
              : "hidden"
          }
        >
          <div
            className={
              show
                ? "fixed top-[70px] w-auto h-[100%] md:h-[91vh] bg-[#0a81d8] md:flex flex-row md:flex-col justify-between rounded-lg hidden "
                : "fixed md:top-[70px] w-full md:w-auto h-full md:h-[91vh] divide-y-2 divide-[#1F2937] bg-[#0a81d8] flex flex-col md:overflow-clip overflow-scroll md:flex-col justify-between md:rounded-lg z-20"
            }
          >
            <div className="divide-y-2 divide-[#1F2937] w-full ">
              <div className={show ? "hidden" : "block"}>
                <div className="hidden md:flex flex-row justify-between md:w-[248px] h-20 mx-auto w-full px-6">
                  <div className="my-auto">
                    <p className="font-semibold text-xl  ">AKE Inc</p>
                    <p className="font-semibold text-xs ">Your Role: ADMIN</p>
                  </div>
                  <FaQuestionCircle
                    size={25}
                    className="text-green-600 my-auto "
                  />
                </div>
              </div>
              <div className="flex flex-col gap-y-4 p-4">
                <div
                  onClick={() => {
                    setActive("dashboard"), onlyWidth < 768 && setShow(!show);
                  }}
                  className={
                    active === "dashboard"
                      ? "flex flex-row gap-x-4 text-[#10B981] cursor-pointer bg-gray-500 bg-opacity-20 p-2"
                      : "flex flex-row gap-x-4 hover:text-[#10B981] cursor-pointer p-2"
                  }
                >
                  <MdSpaceDashboard size={25} />
                  <p className={show ? "hidden" : "block"}>Dashboard</p>
                </div>
                <div
                  onClick={() => {
                    setActive("customers"), onlyWidth < 768 && setShow(!show);
                  }}
                  className={
                    active === "customers"
                      ? "flex flex-row gap-x-4 text-[#10B981] cursor-pointer bg-gray-500 bg-opacity-20 p-2"
                      : "flex flex-row gap-x-4 hover:text-[#10B981] cursor-pointer p-2"
                  }
                >
                  <FaUserFriends size={25} />
                  <p className={show ? "hidden" : "block"}>Users</p>
                </div>
                <div
                  onClick={() => {
                    setActive("products"), onlyWidth < 768 && setShow(!show);
                  }}
                  className={
                    active === "products"
                      ? "flex flex-row gap-x-4 text-[#10B981] cursor-pointer bg-gray-500 bg-opacity-20 p-2"
                      : "flex flex-row gap-x-4 hover:text-[#10B981] cursor-pointer p-2"
                  }
                >
                  <RiShoppingBagFill size={25} />
                  <p className={show ? "hidden" : "block"}>Products</p>
                </div>
                <div
                  onClick={() => {
                    setActive("elevators"), onlyWidth < 768 && setShow(!show);
                  }}
                  className={
                    active === "elevators"
                      ? "flex flex-row gap-x-4 text-[#10B981] cursor-pointer bg-gray-500 bg-opacity-20 p-2"
                      : "flex flex-row gap-x-4 hover:text-[#10B981] cursor-pointer p-2"
                  }
                >
                  <GiElevator size={25} />
                  <p className={show ? "hidden" : "block"}>Elevators</p>
                </div>
                <div
                  onClick={() => {
                    setActive("account"), onlyWidth < 768 && setShow(!show);
                  }}
                  className={
                    active === "account"
                      ? "flex flex-row gap-x-4 text-[#10B981] cursor-pointer bg-gray-500 bg-opacity-20 p-2"
                      : "flex flex-row gap-x-4 hover:text-[#10B981] cursor-pointer p-2"
                  }
                >
                  <FaUserAlt size={25} />
                  <p className={show ? "hidden" : "block"}>Account</p>
                </div>
                <div
                  onClick={() => {
                    setActive("settings"), onlyWidth < 768 && setShow(!show);
                  }}
                  className={
                    active === "settings"
                      ? "flex flex-row gap-x-4 text-[#10B981] cursor-pointer bg-gray-500 bg-opacity-20 p-2"
                      : "flex flex-row gap-x-4 hover:text-[#10B981] cursor-pointer p-2"
                  }
                >
                  <MdSettings size={25} />
                  <p className={show ? "hidden" : "block"}>Settings</p>
                </div>
                {/* <Link href="/login">
                  <div className="flex flex-row gap-x-4 hover:text-[#10B981] cursor-pointer p-2">
                    <FaLock size={20} />
                    <p className={show ? "hidden" : "block"}>Login</p>
                  </div>
                </Link>
                <Link href="/register">
                  <div className="flex flex-row gap-x-4 hover:text-[#10B981] cursor-pointer p-2">
                    <FaUserPlus size={20} />
                    <p className={show ? "hidden" : "block"}>Register</p>
                  </div>
                </Link> */}
              </div>
            </div>
            <div className={show ? "hidden" : "flex flex-col gap-y-2 p-4"}>
              <p className="text-base">Need more Features</p>
              <p className="text-[#9CA3AF] text-xs ">
                Check out our Other Offer
              </p>
              <img
                src="https://i.hizliresim.com/pd2th89.png"
                alt="offer"
                className="w-[160px] h-[136px] object-cover mx-auto"
              />
              <a
                href="https://ake.com.tr/asansor-sistemleri"
                target="_blank"
                rel="noreferrer"
                className="flex flex-row items-center justify-center gap-x-4 bg-green-500  p-2 rounded-lg"
              >
                Get Offer <RiExternalLinkLine size={25} />
              </a>
            </div>
          </div>
        </div>
        <div
          className={
            show
              ? "pt-[70px] text-white w-full h-auto "
              : "pt-[70px] text-white w-full h-full pl-[165px] "
          }
        >
          {active === "dashboard" ? (
            <DashboardMain state={show} />
          ) : active === "customers" ? (
            <Customers />
          ) : active === "products" ? (
            <Products state={show} />
          ) : active === "account" ? (
            <Account />
          ) : active === "settings" ? (
            <Settings />
          ) : active === "elevators" ? (
            <Elevators />
          ) : (
            <DashboardMain />
          )}
        </div>
      </div>
    </div>
  );
}
